name: UpOnlyKB
version: '1.0.4'
main: jp.yoma.upOnlyKB
api-version: '1.13'
authors: [ 紅月妖魔 ]
description: RemoveUnderKB
commands:
  uponlykb:
    description: Reload config
    usage: /uponlykb reload